version: "3.8"

services:
  api:
    build: ./project
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/
    ports:
      - 8000:8000
   

